apiVersion: 1

datasources:
- name: UNIFI
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  password: CHANGEME
  user: unifipoller
  database: unifi
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
  version: 1
  editable: true